title: "Flowinho"
email: contact@flowinho.com
author: Florian Schuttkowski
description: >- # this means to ignore newlines until "baseurl:"
  Hey there. I'm a loving father, part-time podcaster and iOS developer from southern Germany.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flowinho.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: flowinho
github_username: flowinho
show_excerpts: false
future: false
exclude: [vendor]
# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
